
export const brainRegions =
    ["Temporal lobe medial aspect",
        "Entorhinal cortex",
        "Parahippocampal gyrus",
        "Amygdala",
        "Hippocampus",
        "Insula",
        "Orbital Frontal Cortex",
        "Temporal pole",
        "Fusiform gyrus",
        "Temporal lobe",
        "Superior temporal gyrus",
        "Middle temporal gyrus",
        "Inferior temporal gyrus",
        "Transverse temporal gyrus",
        "superior temporal sulcus",
        "Frontal lobe",
        "Superior frontal",
        "Middle frontal gyrus",
        "Inferior frontal gyrus",
        "Pars opercularis",
        "Pars triangularis",
        "Pars orbitalis",
        "Orbitofrontal gyrus",
        "Lateral division",
        "Medial division",
        "Frontal pole",
        "Precentral gyrus",
        "Paracentral lobule",
        "Parietal lobe",
        "Postcentral gyrus",
        "Supramarginal gyrus",
        "Superior parietal lobule",
        "Inferior parietal lobule",
        "Precuneus",
        "Occipital lobe",
        "Lingual gyrus",
        "Pericalcarine cortex",
        "Cuneus cortex",
        "Lateral occipital cortex",
        "Cingulate cortex",
        "Rostral anterior",
        "Caudal anterior",
        "Posterior",
        "Isthmus"
    ]